### ISSUE TITLE
Can't install baboossh==1.1.0

### ISSUE THREAD

**Issue by ghost** [cybiere/baboossh#3]
Hi,

it seems everytime I want to upgrade baboossh to the latest version, it got stuck on version 1.0.2

Here is the error:
```
Traceback (most recent call last):
  File "/usr/app/bin/baboossh", line 3, in <module>
    from baboossh.shell import BaboosshShell
  File "/usr/app/venvs/baboossh/lib/python3.9/site-packages/baboossh/shell.py", line 13, in <module>
    class BaboosshShell(cmd2.Cmd):
  File "/usr/app/venvs/baboossh/lib/python3.9/site-packages/baboossh/shell.py", line 152, in BaboosshShell
    use_arg = parser_wspace_use.add_argument('name', help='Name of workspace to use', choices_method=getArgWorkspaces)
  File "/usr/app/venvs/baboossh/lib/python3.9/site-packages/cmd2/argparse_custom.py", line 866, in _add_argument_wrapper
    new_arg = orig_actions_container_add_argument(self, *args, **kwargs)
  File "/usr/lib/python3.9/argparse.py", line 1431, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choices_method'
```

**Comment by cybiere** [comment]
Hi ! 
Thanks for your feedback
This is due to an update in one of the dependencies, I'm working on it. In the meantime, the code itself is fixed in the `dev` branch, you can pull it from git and install it using `pip install .`, it _should_ work. 
I'm not that fluent with python packaging, but I'm working on fixing that, sorry for the trouble !

**Comment by ghost** [comment]
Everything is ok now :smile:
```
pipx install baboossh
  installed package baboossh 1.1.1, installed using Python 3.9.9
  These apps are now globally available
    - baboossh
done! ✨ 🌟 ✨
```

```
baboossh
9 extensions loaded.
> First run ? Creating workspaces directory
Workspace default created

  %%%%%/      %%%     %%%%%.      .%%/     %%     %/   /%%%/   ,%%%/  *%%    %%
  %%   %%*   %% %%    %%   %%  %*       % %    /@*  % %%      %%      *%%    %% 
  %%%%%%    %%, %%%   %%%%%%  %    @@@@  %    /@@@  /  %%%%    %%%%   *%%%%%%%% 
  %%   %%% %%%%%%%%,  %%   %%(%          %%         %     %%%     %%% *%%    %% 
  %%%%%%  ,%%     %%  %%%%%%   %%      ,%   %#   %%   %%%%%.  %%%%%.  *%%    %%

Welcome to BabooSSH v1.1.1. To start, use "help -v" to list commands.
[default]> help
```

Good job :wink:

**Comment by cybiere** [comment]
Nice, glad it worked ! I'll be working on repackaging this better as soon as I have the time (famous last words...)
In the meantime, feel free to reach out if you have any bugs or feedback !

**Comment by ghost** [comment]
Merci pour ta réactivité ;-)
